In [2]:
import sagemaker
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import os
import boto3

sm_boto3 = boto3.client('sagemaker')
session = sagemaker.Session()
region = session.boto_region_name
bucket = 'sagemakerbucket-ml'
print("S3 bucket for saving data:" + bucket)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:8                                                                                    │
│                                                                                                  │
│    5 import os                                                                                   │
│    6 import boto3                                                                                │
│    7                                                                                             │
│ ❱  8 sm_boto3 = boto3.client('sagemaker')                                                        │
│    9 session = sagemaker.Session()                                                               │
│   10 region = session.boto_region_name                                                           │
│   11 bucket = 'sagemakerbucket-ml'                                                               │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\boto3\__init__.py:93   │
│ in client                                                                                        │
│                                                                                                  │
│    90 │                                                                                          │
│    91 │   See :py:meth:`boto3.session.Session.client`.                                           │
│    92 │   """                                                                                    │
│ ❱  93 │   return _get_default_session().client(*args, **kwargs)                                  │
│    94                                                                                            │
│    95                                                                                            │
│    96 def resource(*args, **kwargs):                                                             │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\boto3\session.py:337   │
│ in client                                                                                        │
│                                                                                                  │
│   334 │   │   │   # botocore version mismatches in AWS Lambda.                                   │
│   335 │   │   │   del create_client_kwargs['aws_account_id']                                     │
│   336 │   │                                                                                      │
│ ❱ 337 │   │   return self._session.create_client(                                                │
│   338 │   │   │   service_name, **create_client_kwargs                                           │
│   339 │   │   )                                                                                  │
│   340                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\session.py:10 │
│ 31 in create_client                                                                              │
│                                                                                                  │
│   1028 │   │   │   user_agent_creator=user_agent_creator,                                        │
│   1029 │   │   │   auth_token_resolver=self.get_auth_token,                                      │
│   1030 │   │   )                                                                                 │
│ ❱ 1031 │   │   client = client_creator.create_client(                                            │
│   1032 │   │   │   service_name=service_name,                                                    │
│   1033 │   │   │   region_name=region_name,                                                      │
│   1034 │   │   │   is_secure=use_ssl,                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:157 │
│ in create_client                                                                                 │
│                                                                                                  │
│    154 │   │   │   service_model.signing_name                                                    │
│    155 │   │   ):                                                                                │
│    156 │   │   │   auth_token = token                                                            │
│ ❱  157 │   │   client_args = self._get_client_args(                                              │
│    158 │   │   │   service_model,                                                                │
│    159 │   │   │   region_name,                                                                  │
│    160 │   │   │   is_secure,                                                                    │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:557 │
│ in _get_client_args                                                                              │
│                                                                                                  │
│    554 │   │   │   config_store=self._config_store,                                              │
│    555 │   │   │   user_agent_creator=self._user_agent_creator,                                  │
│    556 │   │   )                                                                                 │
│ ❱  557 │   │   return args_creator.get_client_args(                                              │
│    558 │   │   │   service_model,                                                                │
│    559 │   │   │   region_name,                                                                  │
│    560 │   │   │   is_secure,                                                                    │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\args.py:121   │
│ in get_client_args                                                                               │
│                                                                                                  │
│   118 │   │   endpoints_ruleset_data=None,                                                       │
│   119 │   │   partition_data=None,                                                               │
│   120 │   ):                                                                                     │
│ ❱ 121 │   │   final_args = self.compute_client_args(                                             │
│   122 │   │   │   service_model,                                                                 │
│   123 │   │   │   client_config,                                                                 │
│   124 │   │   │   endpoint_bridge,                                                               │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\args.py:259   │
│ in compute_client_args                                                                           │
│                                                                                                  │
│   256 │   │   if configured_endpoint_url is not None:                                            │
│   257 │   │   │   register_feature_id('ENDPOINT_OVERRIDE')                                       │
│   258 │   │                                                                                      │
│ ❱ 259 │   │   endpoint_config = self._compute_endpoint_config(                                   │
│   260 │   │   │   service_name=service_name,                                                     │
│   261 │   │   │   region_name=region_name,                                                       │
│   262 │   │   │   endpoint_url=configured_endpoint_url,                                          │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\args.py:447   │
│ in _compute_endpoint_config                                                                      │
│                                                                                                  │
│   444 │   │   │   )                                                                              │
│   445 │   │   if service_name == 'sts':                                                          │
│   446 │   │   │   return self._compute_sts_endpoint_config(**resolve_endpoint_kwargs)            │
│ ❱ 447 │   │   return self._resolve_endpoint(**resolve_endpoint_kwargs)                           │
│   448 │                                                                                          │
│   449 │   def _compute_s3_endpoint_config(                                                       │
│   450 │   │   self, s3_config, **resolve_endpoint_kwargs                                         │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\args.py:552   │
│ in _resolve_endpoint                                                                             │
│                                                                                                  │
│   549 │   │   is_secure,                                                                         │
│   550 │   │   endpoint_bridge,                                                                   │
│   551 │   ):                                                                                     │
│ ❱ 552 │   │   return endpoint_bridge.resolve(                                                    │
│   553 │   │   │   service_name, region_name, endpoint_url, is_secure                             │
│   554 │   │   )                                                                                  │
│   555                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:671 │
│ in resolve                                                                                       │
│                                                                                                  │
│    668 │   │   use_fips_endpoint = self._resolve_endpoint_variant_config_var(                    │
│    669 │   │   │   'use_fips_endpoint'                                                           │
│    670 │   │   )                                                                                 │
│ ❱  671 │   │   resolved = self.endpoint_resolver.construct_endpoint(                             │
│    672 │   │   │   service_name,                                                                 │
│    673 │   │   │   region_name,                                                                  │
│    674 │   │   │   use_dualstack_endpoint=use_dualstack_endpoint,                                │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\regions.py:23 │
│ 3 in construct_endpoint                                                                          │
│                                                                                                  │
│   230 │   │   │   │   in self._UNSUPPORTED_DUALSTACK_PARTITIONS                                  │
│   231 │   │   │   ):                                                                             │
│   232 │   │   │   │   continue                                                                   │
│ ❱ 233 │   │   │   result = self._endpoint_for_partition(                                         │
│   234 │   │   │   │   partition,                                                                 │
│   235 │   │   │   │   service_name,                                                              │
│   236 │   │   │   │   region_name,                                                               │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\regions.py:28 │
│ 1 in _endpoint_for_partition                                                                     │
│                                                                                                  │
│   278 │   │   │   if 'partitionEndpoint' in service_data:                                        │
│   279 │   │   │   │   region_name = service_data['partitionEndpoint']                            │
│   280 │   │   │   else:                                                                          │
│ ❱ 281 │   │   │   │   raise NoRegionError()                                                      │
│   282 │   │                                                                                      │
│   283 │   │   resolve_kwargs = {                                                                 │
│   284 │   │   │   'partition': partition,                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NoRegionError: You must specify a region.

In [3]:
import sagemaker
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import os
import boto3
from botocore.exceptions import NoRegionError

# ---- STEP 1: Set AWS region ----
region = 'us-east-1'  # N. Virginia
os.environ['AWS_DEFAULT_REGION'] = region

# ---- STEP 2: Create SageMaker + Boto3 sessions ----
try:
    boto_session = boto3.Session(region_name=region)
    sm_boto3 = boto_session.client('sagemaker')
    session = sagemaker.Session(boto_session=boto_session)
    print(f"✅ SageMaker session initialized in region: {region}")
except NoRegionError:
    print("❌ AWS region not set. Please configure region manually.")

# ---- STEP 3: Define S3 bucket ----
bucket = 'sagemakerbucket-ml'
print("✅ S3 bucket for saving data:", bucket)

✅ SageMaker session initialized in region: us-east-1
✅ S3 bucket for saving data: sagemakerbucket-ml

In [ ]:
# ---- STEP 4: Test access to the bucket ----
s3 = boto3.client('s3', region_name=region)
try:
    s3.head_bucket(Bucket=bucket)
    print(f"✅ Successfully connected to S3 bucket: {bucket}")
except Exception as e:
    print(f"⚠️ Could not access S3 bucket: {e}")

In [4]:
df = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\reddit_features.csv")
print(df.head())

                                               title       flair  ...  wnat  work
0                          [d] self-promotion thread  Discussion  ...   0.0   0.0
1  [d] monthly who's hiring and who wants to be h...  Discussion  ...   0.0   0.0
2                        [d] on aaai 2026 discussion    Research  ...   0.0   0.0
3  push your creative models further. vast.ai han...         NaN  ...   0.0   0.0
4         [d] found error at published neurips paper    Research  ...   0.0   0.0

[5 rows x 117 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Columns: 117 entries, title to work
dtypes: float64(115), object(2)
memory usage: 20.2+ KB

In [6]:
df.columns

Index(['title', 'flair', '103m', '18pp', '2025', '2026', '70', 'aaai',
       'accuracy', 'actively',
       ...
       'tool', 'topics', 'tracing', 'trendy', 'variance', 'vast', 'vs',
       'wants', 'wnat', 'work'],
      dtype='object', length=117)

In [7]:
df.isnull().sum()

title    0
flair    2
103m     0
18pp     0
2025     0
        ..
vast     0
vs       0
wants    0
wnat     0
work     0
Length: 117, dtype: int64

In [9]:
# Fill missing flair values with "None"
df['flair'] = df['flair'].fillna("None")

# Verify
print("✅ Missing flair values handled:")
print(df['flair'].isnull().sum(), "missing flairs remaining")

✅ Missing flair values handled:
0 missing flairs remaining

In [10]:
df.to_csv("C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/reddit_features_clean.csv", index=False)
print("✅ Cleaned data saved successfully!")

✅ Cleaned data saved successfully!

In [11]:
# Separate features (X) and labels (y)
X = df.drop(columns=['flair', 'title'])
y = df['flair']

In [12]:
X.head()

   103m  18pp  2025      2026   70  ...      vast   vs  wants  wnat  work
0   0.0   0.0   0.0  0.000000  0.0  ...  0.000000  0.0    0.0   0.0   0.0
1   0.0   0.0   0.0  0.000000  0.0  ...  0.000000  0.0    0.5   0.0   0.0
2   0.0   0.0   0.0  0.529278  0.0  ...  0.000000  0.0    0.0   0.0   0.0
3   0.0   0.0   0.0  0.000000  0.0  ...  0.391076  0.0    0.0   0.0   0.0
4   0.0   0.0   0.0  0.000000  0.0  ...  0.000000  0.0    0.0   0.0   0.0

[5 rows x 115 columns]

In [13]:
y.unique()

array(['Discussion', 'Research', 'None', 'Project'], dtype=object)

In [14]:
y.head()

0    Discussion
1    Discussion
2      Research
3          None
4      Research
Name: flair, dtype: object

In [15]:
# Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [16]:
trainX=pd.DataFrame(X_train)
trainX['flair']=y_train

testX=pd.DataFrame(X_test)
testX['flair']=y_test

In [17]:
trainX.to_csv("C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/train-V-1.csv", index=False)
testX.to_csv("C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/test-V-1.csv", index=False)

In [18]:
#send data to s3 bucket
sk_prefix="sagemaker/reddit-flair-classification/sklearncontainer"
trainpath = session.upload_data(
    path="C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/train-V-1.csv",
    bucket=bucket,
    key_prefix=sk_prefix
)

testpath = session.upload_data(
    path="C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/test-V-1.csv",
    bucket=bucket,
    key_prefix=sk_prefix
)

print("✅ Training data uploaded to S3:", trainpath)
print("✅ Testing data uploaded to S3:", testpath)

✅ Training data uploaded to S3: s3://sagemakerbucket-ml/sagemaker/reddit-flair-classification/sklearncontainer/train-V-1.csv
✅ Testing data uploaded to S3: s3://sagemakerbucket-ml/sagemaker/reddit-flair-classification/sklearncontainer/test-V-1.csv

In [ ]:
%%writefile script.py
import argparse
import os
import pandas as pd
import joblib
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder



if __name__ == "__main__":
    # ---------- 1. Parse SageMaker Arguments ----------
    parser = argparse.ArgumentParser()

    # Hyperparameters
    parser.add_argument("--n-estimators", type=int, default=100)
    parser.add_argument("--max-depth", type=int, default=None)
    parser.add_argument("--min-samples-split", type=int, default=2)
    parser.add_argument("--min-samples-leaf", type=int, default=1)

    # Directories and files
    parser.add_argument("--model-dir", type=str, default=os.environ.get("SM_MODEL_DIR"))
    parser.add_argument("--train", type=str, default=os.environ.get("SM_CHANNEL_TRAIN", ""))
    parser.add_argument("--test", type=str, default=os.environ.get("SM_CHANNEL_TEST", ""))
    parser.add_argument("--train-file", type=str, default="train-V-1.csv")
    parser.add_argument("--test-file", type=str, default="test-V-1.csv")

    args, _ = parser.parse_known_args()

    # ---------- 2. Display environment info ----------
    print("📦 SKLearn Version:", sklearn.__version__)
    print("📦 Joblib Version:", joblib.__version__)
    print("📁 Training directory:", args.train)
    print("📁 Testing directory:", args.test)

    # ---------- 3. Read training and test data ----------
    print("[INFO] Reading data...\n")
    train_path = os.path.join(args.train, args.train_file)
    test_path = os.path.join(args.test, args.test_file)

    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)

    print("✅ Train shape:", train_df.shape)
    print("✅ Test shape:", test_df.shape)

    # ---------- 4. Encode labels and prepare features ----------
    le = LabelEncoder()
    train_df["flair"] = le.fit_transform(train_df["flair"].astype(str))
    test_df["flair"] = le.transform(test_df["flair"].astype(str))

    X_train = train_df.drop(columns=["flair"], errors="ignore")
    y_train = train_df["flair"]
    X_test = test_df.drop(columns=["flair"], errors="ignore")
    y_test = test_df["flair"]

    print("Number of features in training:", X_train.shape[1])
    print("Number of features in testing:", X_test.shape[1])

    # ---------- 5. Train Random Forest ----------
    print("🚀 Training Random Forest Classifier...")
    model = RandomForestClassifier(
        n_estimators=args.n_estimators,
        max_depth=args.max_depth,
        min_samples_split=args.min_samples_split,
        min_samples_leaf=args.min_samples_leaf,
        random_state=42,
        n_jobs=-1
    )
    model.fit(X_train, y_train)

    # ---------- 6. Evaluate ----------
    print("📊 Generating classification report...\n")
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred))

    # ---------- 7. Save trained model and encoder ----------
    os.makedirs(args.model_dir, exist_ok=True)
    model_path = os.path.join(args.model_dir, "model.joblib")
    encoder_path = os.path.join(args.model_dir, "label_encoder.joblib")
    joblib.dump(model, model_path)
    joblib.dump(le, encoder_path)
    print(f"✅ Model saved at: {model_path}")
    print(f"✅ LabelEncoder saved at: {encoder_path}")


# ---------- 8. SageMaker Inference Functions ----------
def model_fn(model_dir):
    """Load the model for inference"""
    model_path = os.path.join(model_dir, "model.joblib")
    encoder_path = os.path.join(model_dir, "label_encoder.joblib")
    print(f"[INFO] Loading model from {model_path}")
    model = joblib.load(model_path)
    le = joblib.load(encoder_path)
    return {"model": model, "encoder": le}

def input_fn(request_body, request_content_type):
    """Deserialize input data"""
    import io
    if request_content_type == "text/csv":
        df = pd.read_csv(io.StringIO(request_body), header=None)
        return df.fillna(0)
    else:
        raise ValueError(f"Unsupported content type: {request_content_type}")

def predict_fn(input_data, model_dict):
    """Make prediction"""
    model = model_dict["model"]
    preds = model.predict(input_data)
    return preds  # numeric predictions

def output_fn(prediction, response_content_type):
    """Serialize prediction output"""
    if response_content_type == "text/csv":
        return ",".join(map(str, prediction))
    else:
        raise ValueError(f"Unsupported content type: {response_content_type}")

Writing script.py

In [69]:
from sagemaker.sklearn.estimator import SKLearn

FRAMEWORK_VERSION = "0.23-1"

sklearn_estimator = SKLearn(
    entry_point="script.py",
    role="arn:aws:iam::375756730874:role/AmazonSageMaker-ExecutionRole",
    instance_count=1,
    instance_type="ml.m5.large",
    framework_version=FRAMEWORK_VERSION,
    base_job_name="RF-custom-sklearn",
    hyperparameters={
        "n_estimators": 100,
        "random_state": 0
    },
    use_spot_instances=True,
    max_wait=7200,     # Max time including spot delay
    max_run=3600       # Max time for the actual training job
)

In [70]:
sklearn_estimator.fit({"train": trainpath, "test": testpath}, wait=True)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: RF-custom-sklearn-2025-10-19-20-18-06-780

2025-10-19 20:18:47 Starting - Starting the training job..
2025-10-19 20:19:25 Downloading - Downloading input data..
2025-10-19 20:19:50 Downloading - Downloading the training image...
2025-10-19 20:20:46 Training - Training image download completed. Training in progress.
2025-10-19 20:20:46 Uploading - Uploading generated training model2025-10-19 20:20:40,369 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training
2025-10-19 20:20:40,373 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2025-10-19 20:20:40,422 sagemaker_sklearn_container.training INFO     Invoking user training script.
2025-10-19 20:20:40,638 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2025-10-19 20:20:40,651 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2025-10-19 20:20:40,665 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
2025-10-19 20:20:40,674 sagemaker-training-toolkit INFO     Invoking user script
Training Env:
{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "test": "/opt/ml/input/data/test",
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_sklearn_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "n_estimators": 100,
        "random_state": 0
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "test": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        },
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "is_master": true,
    "job_name": "RF-custom-sklearn-2025-10-19-20-18-06-780",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-375756730874/RF-custom-sklearn-2025-10-19-20-18-06-780/source/sourcedir.tar.gz",
    "module_name": "script",
    "network_interface_name": "eth0",
    "num_cpus": 2,
    "num_gpus": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "current_instance_type": "ml.m5.large",
        "current_group_name": "homogeneousCluster",
        "hosts": [
            "algo-1"
        ],
        "instance_groups": [
            {
                "instance_group_name": "homogeneousCluster",
                "instance_type": "ml.m5.large",
                "hosts": [
                    "algo-1"
                ]
            }
        ],
        "network_interface_name": "eth0",
        "topology": null
    },
    "user_entry_point": "script.py"
}
Environment variables:
SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"n_estimators":100,"random_state":0}
SM_USER_ENTRY_POINT=script.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null}
SM_INPUT_DATA_CONFIG={"test":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["test","train"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=script
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_sklearn_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=2
SM_NUM_GPUS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-375756730874/RF-custom-sklearn-2025-10-19-20-18-06-780/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"test":"/opt/ml/input/data/test","train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_sklearn_container.training:main","hosts":["algo-1"],"hyperparameters":{"n_estimators":100,"random_state":0},"input_config_dir":"/opt/ml/input/config","input_data_config":{"test":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"},"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"RF-custom-sklearn-2025-10-19-20-18-06-780","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-375756730874/RF-custom-sklearn-2025-10-19-20-18-06-780/source/sourcedir.tar.gz","module_name":"script","network_interface_name":"eth0","num_cpus":2,"num_gpus":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_group_name":"homogeneousCluster","current_host":"algo-1","current_instance_type":"ml.m5.large","hosts":["algo-1"],"instance_groups":[{"hosts":["algo-1"],"instance_group_name":"homogeneousCluster","instance_type":"ml.m5.large"}],"network_interface_name":"eth0","topology":null},"user_entry_point":"script.py"}
SM_USER_ARGS=["--n_estimators","100","--random_state","0"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TEST=/opt/ml/input/data/test
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_HP_N_ESTIMATORS=100
SM_HP_RANDOM_STATE=0
PYTHONPATH=/opt/ml/code:/miniconda3/bin:/miniconda3/lib/python37.zip:/miniconda3/lib/python3.7:/miniconda3/lib/python3.7/lib-dynload:/miniconda3/lib/python3.7/site-packages
Invoking script with the following command:
/miniconda3/bin/python script.py --n_estimators 100 --random_state 0
📦 SKLearn Version: 0.23.2
📦 Joblib Version: 1.2.0
📁 Training directory: /opt/ml/input/data/train
📁 Testing directory: /opt/ml/input/data/test
[INFO] Reading data...
✅ Train shape: (17, 116)
✅ Test shape: (5, 116)
Number of features in training: 115
Number of features in testing: 115
🚀 Training Random Forest Classifier...
📊 Generating classification report...
/miniconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
              precision    recall  f1-score   support
           0       0.60      1.00      0.75         3
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
    accuracy                           0.60         5
   macro avg       0.20      0.33      0.25         5
weighted avg       0.36      0.60      0.45         5
✅ Model saved at: /opt/ml/model/model.joblib
✅ LabelEncoder saved at: /opt/ml/model/label_encoder.joblib
2025-10-19 20:20:42,050 sagemaker-containers INFO     Reporting training SUCCESS

2025-10-19 20:20:59 Completed - Training job completed
Training seconds: 94
Billable seconds: 35
Managed Spot Training savings: 62.8%

In [3]:
sklearn_estimator.latest_training_job.wait(logs="None")
artifact = sm_boto3.describe_training_job(
    TrainingJobName=sklearn_estimator.latest_training_job.name)["ModelArtifacts"]["S3ModelArtifacts"]
print("✅ Model artifacts located at:", artifact)

NameError: name 'sklearn_estimator' is not defined

In [72]:
artifact

's3://sagemaker-us-east-1-375756730874/RF-custom-sklearn-2025-10-19-20-18-06-780/output/model.tar.gz'

In [73]:
from sagemaker.sklearn.model import SKLearnModel
from time import gmtime, strftime

model_name = "Custom-sklearn-model-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
model = SKLearnModel(
    name=model_name,
    model_data=artifact,
    role="arn:aws:iam::375756730874:role/AmazonSageMaker-ExecutionRole",
    entry_point="script.py",
    framework_version=FRAMEWORK_VERSION
)

In [74]:
model

In [75]:
model_name

'Custom-sklearn-model-2025-10-19-20-32-52'

In [2]:
endpoint_name = "Custom-sklearn-model-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
print("EndpointName={}".format(endpoint_name))
predictor = model.deploy(
    initial_instance_count=1,
    instance_type="ml.m4.xlarge",
    endpoint_name=endpoint_name
)

NameError: name 'strftime' is not defined

In [1]:
predictor

NameError: name 'predictor' is not defined

In [86]:
endpoint_name

'Custom-sklearn-model-2025-10-19-20-33-33'

In [84]:
import pandas as pd

test_df = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\train-V-1.csv")
test_df.head()

   103m      18pp  2025  2026        70  ...   vs  wants      wnat  work       flair
0   0.0  0.306601   0.0   0.0  0.306601  ...  0.0    0.0  0.000000   0.0    Research
1   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.5  0.000000   0.0  Discussion
2   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.000000   0.0  Discussion
3   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.000000   0.0  Discussion
4   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.464347   0.0  Discussion

[5 rows x 116 columns]

In [87]:
# Drop target columns and keep only numeric features
X_test = test_df.drop(columns=["flair",], errors="ignore")
X_test.head()

   103m      18pp  2025  2026        70  ...  vast   vs  wants      wnat  work
0   0.0  0.306601   0.0   0.0  0.306601  ...   0.0  0.0    0.0  0.000000   0.0
1   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.5  0.000000   0.0
2   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.000000   0.0
3   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.000000   0.0
4   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.464347   0.0

[5 rows x 115 columns]

In [88]:


csv_input = X.head(5).to_csv(index=False, header=False)
response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})
print(response)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 csv_input = X.head(5).to_csv(index=False, header=False)                                      │
│ ❱ 2 response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})            │
│   3 print(response)                                                                              │
│   4                                                                                              │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\sagemaker\base_predict │
│ or.py:212 in predict                                                                             │
│                                                                                                  │
│   209 │   │   if inference_component_name:                                                       │
│   210 │   │   │   request_args["InferenceComponentName"] = inference_component_name              │
│   211 │   │                                                                                      │
│ ❱ 212 │   │   response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**req   │
│   213 │   │   return self._handle_response(response)                                             │
│   214 │                                                                                          │
│   215 │   def _handle_response(self, response):                                                  │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:602 │
│ in _api_call                                                                                     │
│                                                                                                  │
│    599 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    600 │   │   │   │   )                                                                         │
│    601 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  602 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    603 │   │                                                                                     │
│    604 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    605                                                                                           │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:107 │
│ 8 in _make_api_call                                                                              │
│                                                                                                  │
│   1075 │   │   │   │   'error_code_override'                                                     │
│   1076 │   │   │   ) or error_info.get("Code")                                                   │
│   1077 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1078 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1079 │   │   else:                                                                             │
│   1080 │   │   │   return parsed_response                                                        │
│   1081                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500)
from primary with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is
overloaded or there is an error in the application.</p>
". See
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpo
ints/Custom-sklearn-model-2025-10-19-20-33-33 in account 375756730874 for more information.

In [89]:
import pandas as pd
from sagemaker.sklearn.model import SKLearnPredictor

# Load your CSV
X_test = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\train-V-1.csv")
X_test = X_test.drop(columns=["flair"], errors="ignore")  # only features

# Make sure columns are sorted in the same order as training
X_test = X_test.reindex(sorted(X_test.columns), axis=1)

# Take a few rows
csv_input = X_test.head(5).to_csv(index=False, header=False)

# Use your deployed predictor
predictor = SKLearnPredictor(endpoint_name="Custom-sklearn-model-2025-10-19-20-33-33")
response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})

# Decode
preds = response.decode("utf-8").strip().split(",")
print("Predicted labels (numeric):", preds)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:16                                                                                   │
│                                                                                                  │
│   13                                                                                             │
│   14 # Use your deployed predictor                                                               │
│   15 predictor = SKLearnPredictor(endpoint_name="Custom-sklearn-model-2025-10-19-20-33-33")      │
│ ❱ 16 response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})           │
│   17                                                                                             │
│   18 # Decode                                                                                    │
│   19 preds = response.decode("utf-8").strip().split(",")                                         │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\sagemaker\base_predict │
│ or.py:212 in predict                                                                             │
│                                                                                                  │
│   209 │   │   if inference_component_name:                                                       │
│   210 │   │   │   request_args["InferenceComponentName"] = inference_component_name              │
│   211 │   │                                                                                      │
│ ❱ 212 │   │   response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**req   │
│   213 │   │   return self._handle_response(response)                                             │
│   214 │                                                                                          │
│   215 │   def _handle_response(self, response):                                                  │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:602 │
│ in _api_call                                                                                     │
│                                                                                                  │
│    599 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    600 │   │   │   │   )                                                                         │
│    601 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  602 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    603 │   │                                                                                     │
│    604 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    605                                                                                           │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:107 │
│ 8 in _make_api_call                                                                              │
│                                                                                                  │
│   1075 │   │   │   │   'error_code_override'                                                     │
│   1076 │   │   │   ) or error_info.get("Code")                                                   │
│   1077 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1078 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1079 │   │   else:                                                                             │
│   1080 │   │   │   return parsed_response                                                        │
│   1081                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500)
from primary with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is
overloaded or there is an error in the application.</p>
". See
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpo
ints/Custom-sklearn-model-2025-10-19-20-33-33 in account 375756730874 for more information.

In [ ]:
import boto3
import tarfile
import os
import joblib
import pandas as pd

# --- 1. Setup ---
s3_bucket = "sagemaker-us-east-1-375756730874"  # e.g., "sagemaker-your-bucket"
model_artifacts_key = "RF-custom-sklearn-2025-10-19-20-18-06-780/output/model.tar.gz"  # e.g., "sklearn/reddit-flair-classification/model.tar.gz"
local_dir = "model_local"

os.makedirs(local_dir, exist_ok=True)

# --- 2. Download model artifacts from S3 ---
s3 = boto3.client("s3")
#s3 = boto3.client("s3")
local_tar_path = os.path.join(local_dir, "model.tar.gz")
s3.download_file(s3_bucket, model_artifacts_key, local_tar_path)
print(f"✅ Downloaded model artifacts to {local_tar_path}")

# --- 3. Extract model and encoder ---
with tarfile.open(local_tar_path, "r:gz") as tar:
    tar.extractall(path=local_dir)
print(f"✅ Extracted artifacts to {local_dir}")

model_path = os.path.join(local_dir, "model.joblib")
encoder_path = os.path.join(local_dir, "label_encoder.joblib")

model = joblib.load(model_path)
le = joblib.load(encoder_path)
print("✅ Model and LabelEncoder loaded")

# --- 4. Load your CSV for prediction ---
data_path = "C:/Users/user/Desktop/twitter-sentiment-sagemaker/src/data/processed/train-V-1.csv"
df = pd.read_csv(data_path)

# Keep only numeric features, ensure same order as training
X = df.drop(columns=["flair"], errors="ignore")
X = X.reindex(sorted(X.columns), axis=1)  # important: keep column order consistent
X = X.fillna(0)  # handle missing values

# --- 5. Predict ---
pred_numeric = model.predict(X.head(5))
pred_labels = le.inverse_transform(pred_numeric)

print("Numeric predictions:", pred_numeric)
print("Decoded flair labels:", pred_labels)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:18                                                                                   │
│                                                                                                  │
│   15 s3 = boto3.client("s3")                                                                     │
│   16 #s3 = boto3.client("s3")                                                                    │
│   17 local_tar_path = os.path.join(local_dir, "model.tar.gz")                                    │
│ ❱ 18 s3.download_file(s3_bucket, model_artifacts_key, local_tar_path)                            │
│   19 print(f"✅ Downloaded model artifacts to {local_tar_path}")                                 │
│   20                                                                                             │
│   21 # --- 3. Extract model and encoder ---                                                      │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\boto3\s3\inject.py:223 │
│ in download_file                                                                                 │
│                                                                                                  │
│   220 │   │   transfer.                                                                          │
│   221 │   """                                                                                    │
│   222 │   with S3Transfer(self, Config) as transfer:                                             │
│ ❱ 223 │   │   return transfer.download_file(                                                     │
│   224 │   │   │   bucket=Bucket,                                                                 │
│   225 │   │   │   key=Key,                                                                       │
│   226 │   │   │   filename=Filename,                                                             │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\boto3\s3\transfer.py:4 │
│ 07 in download_file                                                                              │
│                                                                                                  │
│   404 │   │   │   bucket, key, filename, extra_args, subscribers                                 │
│   405 │   │   )                                                                                  │
│   406 │   │   try:                                                                               │
│ ❱ 407 │   │   │   future.result()                                                                │
│   408 │   │   # This is for backwards compatibility where when retries are                       │
│   409 │   │   # exceeded we need to throw the same error from boto3 instead of                   │
│   410 │   │   # s3transfer's built in RetriesExceededError as current users are                  │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\s3transfer\futures.py: │
│ 111 in result                                                                                    │
│                                                                                                  │
│   108 │   │   │   # Usually the result() method blocks until the transfer is done,               │
│   109 │   │   │   # however if a KeyboardInterrupt is raised we want want to exit                │
│   110 │   │   │   # out of this and propagate the exception.                                     │
│ ❱ 111 │   │   │   return self._coordinator.result()                                              │
│   112 │   │   except KeyboardInterrupt as e:                                                     │
│   113 │   │   │   self.cancel()                                                                  │
│   114 │   │   │   raise e                                                                        │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\s3transfer\futures.py: │
│ 287 in result                                                                                    │
│                                                                                                  │
│   284 │   │   # Once done waiting, raise an exception if present or return the                   │
│   285 │   │   # final result.                                                                    │
│   286 │   │   if self._exception:                                                                │
│ ❱ 287 │   │   │   raise self._exception                                                          │
│   288 │   │   return self._result                                                                │
│   289 │                                                                                          │
│   290 │   def cancel(self, msg='', exc_type=CancelledError):                                     │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\s3transfer\tasks.py:27 │
│ 2 in _main                                                                                       │
│                                                                                                  │
│   269 │   │   │                                                                                  │
│   270 │   │   │   # Call the submit method to start submitting tasks to execute the              │
│   271 │   │   │   # transfer.                                                                    │
│ ❱ 272 │   │   │   self._submit(transfer_future=transfer_future, **kwargs)                        │
│   273 │   │   except BaseException as e:                                                         │
│   274 │   │   │   # If there was an exception raised during the submission of task               │
│   275 │   │   │   # there is a chance that the final task that signals if a transfer             │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\s3transfer\download.py │
│ :359 in _submit                                                                                  │
│                                                                                                  │
│   356 │   │   │   transfer_future.meta.size is None                                              │
│   357 │   │   │   or transfer_future.meta.etag is None                                           │
│   358 │   │   ):                                                                                 │
│ ❱ 359 │   │   │   response = client.head_object(                                                 │
│   360 │   │   │   │   Bucket=transfer_future.meta.call_args.bucket,                              │
│   361 │   │   │   │   Key=transfer_future.meta.call_args.key,                                    │
│   362 │   │   │   │   **transfer_future.meta.call_args.extra_args,                               │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:602 │
│ in _api_call                                                                                     │
│                                                                                                  │
│    599 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    600 │   │   │   │   )                                                                         │
│    601 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  602 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    603 │   │                                                                                     │
│    604 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    605                                                                                           │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:107 │
│ 8 in _make_api_call                                                                              │
│                                                                                                  │
│   1075 │   │   │   │   'error_code_override'                                                     │
│   1076 │   │   │   ) or error_info.get("Code")                                                   │
│   1077 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1078 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1079 │   │   else:                                                                             │
│   1080 │   │   │   return parsed_response                                                        │
│   1081                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

In [63]:
import pandas as pd

test_df = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\train-V-1.csv")
test_df.head()

   103m      18pp  2025  2026        70  ...   vs  wants      wnat  work       flair
0   0.0  0.306601   0.0   0.0  0.306601  ...  0.0    0.0  0.000000   0.0    Research
1   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.5  0.000000   0.0  Discussion
2   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.000000   0.0  Discussion
3   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.000000   0.0  Discussion
4   0.0  0.000000   0.0   0.0  0.000000  ...  0.0    0.0  0.464347   0.0  Discussion

[5 rows x 116 columns]

In [64]:
test_df.columns

Index(['103m', '18pp', '2025', '2026', '70', 'aaai', 'accuracy', 'actively',
       'agent', 'agentic',
       ...
       'topics', 'tracing', 'trendy', 'variance', 'vast', 'vs', 'wants',
       'wnat', 'work', 'flair'],
      dtype='object', length=116)

In [65]:
# Drop target columns and keep only numeric features
X_test = test_df.drop(columns=["flair",], errors="ignore")
X_test.head()

   103m      18pp  2025  2026        70  ...  vast   vs  wants      wnat  work
0   0.0  0.306601   0.0   0.0  0.306601  ...   0.0  0.0    0.0  0.000000   0.0
1   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.5  0.000000   0.0
2   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.000000   0.0
3   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.000000   0.0
4   0.0  0.000000   0.0   0.0  0.000000  ...   0.0  0.0    0.0  0.464347   0.0

[5 rows x 115 columns]

In [66]:
#import pandas as pd

#test_df = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\train-V-1.csv")

# Drop target columns and keep only numeric features
#X_test = test_df.drop(columns=["flair",], errors="ignore")

# Ensure same feature order as during training
#X_test = X_test.reindex(sorted(X_test.columns), axis=1)

# Prepare small sample (no header, no index)
csv_input = X_test.head(5).to_csv(index=False, header=False)

# Make prediction
response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})
print("Raw response:", response)

# Decode
try:
    preds = response.decode("utf-8").strip().split(",")
    print("Predicted flair labels:", preds)
except Exception as e:
    print("⚠️ Decode error:", e)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:15                                                                                   │
│                                                                                                  │
│   12 csv_input = X_test.head(5).to_csv(index=False, header=False)                                │
│   13                                                                                             │
│   14 # Make prediction                                                                           │
│ ❱ 15 response = predictor.predict(csv_input, initial_args={"ContentType": "text/csv"})           │
│   16 print("Raw response:", response)                                                            │
│   17                                                                                             │
│   18 # Decode                                                                                    │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\sagemaker\base_predict │
│ or.py:212 in predict                                                                             │
│                                                                                                  │
│   209 │   │   if inference_component_name:                                                       │
│   210 │   │   │   request_args["InferenceComponentName"] = inference_component_name              │
│   211 │   │                                                                                      │
│ ❱ 212 │   │   response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**req   │
│   213 │   │   return self._handle_response(response)                                             │
│   214 │                                                                                          │
│   215 │   def _handle_response(self, response):                                                  │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:602 │
│ in _api_call                                                                                     │
│                                                                                                  │
│    599 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    600 │   │   │   │   )                                                                         │
│    601 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  602 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    603 │   │                                                                                     │
│    604 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    605                                                                                           │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\context.py:12 │
│ 3 in wrapper                                                                                     │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\botocore\client.py:107 │
│ 8 in _make_api_call                                                                              │
│                                                                                                  │
│   1075 │   │   │   │   'error_code_override'                                                     │
│   1076 │   │   │   ) or error_info.get("Code")                                                   │
│   1077 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1078 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1079 │   │   else:                                                                             │
│   1080 │   │   │   return parsed_response                                                        │
│   1081                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500)
from primary with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is
overloaded or there is an error in the application.</p>
". See
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpo
ints/Custom-sklearn-model-2025-10-19-17-58-45 in account 375756730874 for more information.

In [50]:
import pandas as pd

df = pd.read_csv(r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\src\data\processed\reddit_features_clean.csv")

# Drop non-feature columns
X = df.drop(columns=["flair", "title"], errors='ignore')

# Verify all are numeric
print("Columns:", X.columns.tolist())
print("Any non-numeric?", not X.applymap(lambda x: isinstance(x, (int, float))).all().all())

Columns: ['103m', '18pp', '2025', '2026', '70', 'aaai', 'accuracy', 'actively', 'agent', 'agentic', 'agents', 'ai', 'analysis', 'areas', 'beens', 'book', 'calling', 'commoditized', 'context', 'control', 'covariate', 'creative', 'credits', 'desktop', 'dgx', 'discussion', 'emerging', 'engineering', 'english', 'environment', 'error', 'evaluations', 'execution', 'experience', 'feedback', 'gcp', 'general', 'gpus', 'handles', 'hear', 'heating', 'hired', 'hiring', 'house', 'iclr', 'implementation', 'improve', 'industry', 'internal', 'interview', 'interviewers', 'jobs', 'json', 'learning', 'level', 'like', 'llm', 'llms', 'looking', 'mac', 'mila', 'minimax', 'ml', 'mle', 'modelling', 'models', 'moe', 'monthly', 'moving', 'multi', 'neurips', 'nlp', 'numerical', 'nvidia', 'open', 'opik', 'optimization', 'outperforms', 'overlapping', 'paper', 'people', 'phd', 'plain', 'pro', 'promotion', 'published', 'purpose', 'pursued', 'push', 'quebec', 'reinforcement', 'research', 'review', 'right', 'rl', 'roles', 'schedule', 'scratch', 'self', 'sequences', 'shift', 'source', 'squeezed', 'students', 'thread', 'tool', 'topics', 'tracing', 'trendy', 'variance', 'vast', 'vs', 'wants', 'wnat', 'work']

C:\Users\user\AppData\Local\Temp\ipykernel_17844\3590976387.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print("Any non-numeric?", not X.applymap(lambda x: isinstance(x, (int, float))).all().all())

Any non-numeric? False

In [51]:
csv_input = X.head(5).to_csv(index=False, header=False)

In [52]:
print("CSV Input:\n", csv_input)

CSV Input:
 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5773502691896258,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5773502691896258,0.0,0.0,0.0,0.0,0.0,0.5773502691896258,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
0.0,0.0,0.0,0.5292778985414464,0.0,0.5999437082408443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5999437082408443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2869787107320743,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3910761263459576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3910761263459576,0.3910761263459576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3910761263459576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3910761263459576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3910761263459576,0.0,0.0,0.0,0.0
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5410445361556813,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4773163068139914,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4321004085182273,0.0,0.0,0.0,0.0,0.0,0.5410445361556813,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
print("Number of features in CSV:", X.shape[1])

Number of features in CSV: 115

In [54]:
import boto3
import joblib
import os

s3 = boto3.client("s3")

# Path from when you deployed your model
# Example: "s3://your-bucket-name/sagemaker/sklearn-model/model.tar.gz"
model_s3_path = "s3://sagemaker-us-east-1-375756730874/RF-custom-sklearn-2025-10-19-17-53-58-999/output/model.tar.gz"

# Split bucket and key
path_parts = model_s3_path.replace("s3://", "").split("/", 1)
bucket_name = path_parts[0]
key = path_parts[1]

# Download locally
os.makedirs("model_dir", exist_ok=True)
local_path = "model_dir/model.tar.gz"
s3.download_file(bucket_name, key, local_path)

print("✅ Model downloaded to:", local_path)

✅ Model downloaded to: model_dir/model.tar.gz

In [55]:
import tarfile

# Extract model archive
with tarfile.open(local_path, "r:gz") as tar:
    tar.extractall(path="model_dir")

# Find the joblib file
import glob
joblib_path = glob.glob("model_dir/**/*.joblib", recursive=True)[0]
print("Found model file:", joblib_path)

# Load it
model = joblib.load(joblib_path)
print("✅ Model loaded successfully.")

C:\Users\user\AppData\Local\Temp\ipykernel_17844\1501646398.py:5: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path="model_dir")

Found model file: model_dir\model.joblib

c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:13                                                                                   │
│                                                                                                  │
│   10 print("Found model file:", joblib_path)                                                     │
│   11                                                                                             │
│   12 # Load it                                                                                   │
│ ❱ 13 model = joblib.load(joblib_path)                                                            │
│   14 print("✅ Model loaded successfully.")                                                      │
│   15                                                                                             │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\joblib\numpy_pickle.py │
│ :749 in load                                                                                     │
│                                                                                                  │
│   746 │   │   │   │   # A memory-mapped array has to be mapped with the endianness               │
│   747 │   │   │   │   # it has been written with. Other arrays are coerced to the                │
│   748 │   │   │   │   # native endianness of the host system.                                    │
│ ❱ 749 │   │   │   │   obj = _unpickle(                                                           │
│   750 │   │   │   │   │   fobj,                                                                  │
│   751 │   │   │   │   │   ensure_native_byte_order=ensure_native_byte_order,                     │
│   752 │   │   │   │   │   filename=filename,                                                     │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\joblib\numpy_pickle.py │
│ :626 in _unpickle                                                                                │
│                                                                                                  │
│   623 │   )                                                                                      │
│   624 │   obj = None                                                                             │
│   625 │   try:                                                                                   │
│ ❱ 626 │   │   obj = unpickler.load()                                                             │
│   627 │   │   if unpickler.compat_mode:                                                          │
│   628 │   │   │   warnings.warn(                                                                 │
│   629 │   │   │   │   "The file '%s' has been generated with a "                                 │
│                                                                                                  │
│ C:\Program Files\Python313\Lib\pickle.py:1256 in load                                            │
│                                                                                                  │
│   1253 │   │   │   │   if not key:                                                               │
│   1254 │   │   │   │   │   raise EOFError                                                        │
│   1255 │   │   │   │   assert isinstance(key, bytes_types)                                       │
│ ❱ 1256 │   │   │   │   dispatch[key[0]](self)                                                    │
│   1257 │   │   except _Stop as stopinst:                                                         │
│   1258 │   │   │   return stopinst.value                                                         │
│   1259                                                                                           │
│                                                                                                  │
│ c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\joblib\numpy_pickle.py │
│ :446 in load_build                                                                               │
│                                                                                                  │
│   443 │   │   replace them directly in the stack of pickler.                                     │
│   444 │   │   NDArrayWrapper is used for backward compatibility with joblib <= 0.9.              │
│   445 │   │   """                                                                                │
│ ❱ 446 │   │   Unpickler.load_build(self)                                                         │
│   447 │   │                                                                                      │
│   448 │   │   # For backward compatibility, we support NDArrayWrapper objects.                   │
│   449 │   │   if isinstance(self.stack[-1], (NDArrayWrapper, NumpyArrayWrapper)):                │
│                                                                                                  │
│ C:\Program Files\Python313\Lib\pickle.py:1760 in load_build                                      │
│                                                                                                  │
│   1757 │   │   inst = stack[-1]                                                                  │
│   1758 │   │   setstate = getattr(inst, "__setstate__", _NoValue)                                │
│   1759 │   │   if setstate is not _NoValue:                                                      │
│ ❱ 1760 │   │   │   setstate(state)                                                               │
│   1761 │   │   │   return                                                                        │
│   1762 │   │   slotstate = None                                                                  │
│   1763 │   │   if isinstance(state, tuple) and len(state) == 2:                                  │
│                                                                                                  │
│ in sklearn.tree._tree.Tree.__setstate__:836                                                      │
│                                                                                                  │
│ in sklearn.tree._tree._check_node_ndarray:1542                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples',
'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8',
'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity',
'<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

In [5]:
import tarfile
import os

tar_path = r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\model.tar.gz"
extract_dir = r"C:\Users\user\Desktop\twitter-sentiment-sagemaker\artifacts"

os.makedirs(extract_dir, exist_ok=True)

with tarfile.open(tar_path, "r:gz") as tar:
    tar.extractall(path=extract_dir)

print("Extracted files:", os.listdir(extract_dir))

Extracted files: ['label_encoder.joblib', 'model.joblib']

C:\Users\user\AppData\Local\Temp\ipykernel_10136\1580076009.py:10: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=extract_dir)

In [6]:
import joblib
import os

model_path = os.path.join(extract_dir, "model.joblib")
encoder_path = os.path.join(extract_dir, "label_encoder.joblib")

model = joblib.load(model_path)
label_encoder = joblib.load(encoder_path)

print("Model and encoder loaded successfully!")

c:\Users\user\Desktop\twitter-sentiment-sagemaker\myenv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]